### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-website#260] opened 2023-08-09 13:52 UTC
I was searching for the reaction HOCO <=> CO + OH on the website (in SMILES: `O[C]=O` <=> `[C-]#[O+]` + `[OH]`), and got the following error:

![image](https://github.com/ReactionMechanismGenerator/RMG-website/assets/16158262/dadbad64-c89e-4c1a-816f-17063f9f1973)

The error persists every time I try this specific query

**Comment by jonwzheng** [comment] 2024-03-18 20:11
Hi Alon:
I looked into this and the root cause is that the Glarborg libraries includes some rates for the reverse reaction that are 0:
https://rmg.mit.edu/database/kinetics/libraries/Glarborg/C1/150/
https://rmg.mit.edu/database/kinetics/libraries/Glarborg/C2/378/
https://rmg.mit.edu/database/kinetics/libraries/Glarborg/C3/478/

and the inverse of 0 results in `nan` which causes a problem with the rendering. I am working on a patch to fix this.

**Comment by jonwzheng** [comment] 2024-03-20 21:24
Fixed with #276

**Closed by jonwzheng** 2024-03-20 21:24 UTC
Labels: Undesired Behavior, Incorrect Behavior, Error
